name: sproutly
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/bgs/
    - assets/images/decorations/
    - assets/images/logo/
    - assets/images/plants/
    - assets/images/ui/
    - assets/images/ui/buttons/
    - assets/images/ui/panels/

  fonts:
    - family: RainyHearts
      fonts:
        - asset: assets/fonts/rainyhearts.ttf
    - family: SproutLands
      fonts:
        - asset: assets/fonts/sproutlands.ttf
